name: RLC CI/CD Pipeline (Tests, Builds, Deploys)

on:
  pull_request:
    branches:
      - staging
    types:
      - closed

jobs:
  test-backend:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'backend')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: |
          # Run your unit tests here
          echo "Run unit tests of backend"

          

  deploy-backend:
    needs: test-backend
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'backend')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Heroku container registry!
        uses: docker/login-action@v1
        #API_KEY MUST COME FROM GITHUB_SECRETS
        with:
          registry: ${{secrets.HEROKU_REGISTRY_BACKEND}}
          username: ${{secrets.HEROKU_REGISTRY_EMAIL}}
          password: ${{secrets.HEROKU_API_KEY}}
      - name: "Build and Deploy to Heroku Registry"
        run: |
          export HEROKU_API_KEY=${{secrets.HEROKU_API_KEY}}}
          echo "Installing heroku..."
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
          cd backend
          echo "Performing to build API docker..."
          docker build -t registry.heroku.com/rlc-backend/web .
          echo "Build completed!"

          echo "Pushing the image into Heroku..."
          docker push registry.heroku.com/rlc-backend/web
          echo "Pushing completed!"

          echo "Releasing the container..."
          heroku container:release web -a rlc-backend
          echo "Release completed!"

          

  health_check:
    needs: deploy-backend
    runs-on: ubuntu-latest
    steps:
      - name: Health Check
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://rlc-backend-745ce66c9e0c.herokuapp.com/)

          if [ "$response" == "200" ]; then
            echo "Health check passed. Status code: 200"
          else
            echo "Health check failed. Status code: $response"
            exit 1
          fi
